languageCode: "en-us"
baseUrl: ""
title: "Lambros Hatzinikolaou"
author: "Lambros Hatzinicolaou"
theme: "anubis"
paginate: 3
disqusShortname: yourdiscussshortname
googleAnalytics: UA-123-45
enableRobotsTXT: true
enableInlineShortcodes: true
enableEmoji: true

menu:
  main:
  - identifier: archive
    name: Archive
    url: /posts/
    weight: 0
  - identifier: about
    name: About
    url: /about
    weight: 1
 
  
params:
  author: ""
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  customJS:
    - js/main.js # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher

  

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown


