baseURL: 'https://LambrosHatzinikolaou.com'
languageCode: en-us
title: LambrosHatzinikolaou
theme: anubis
paginate: 3
disqusShortname: ''
googleAnalytics: ''
author:
  name: 
params:
  author: Lambros Hatzinikolaou
  description: My personal blog on web development.
  dateFormat: '2021-01-01'
  paginationSinglePost: true
  style: light-without-switcher
  readMore: false
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1

    - identifier: post
      name: Posts
      url: /posts/
      weight: 2
taxonomies:
  category: categories
  tag: tags
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: Dark
    tabWidth: 4